version: 2

services:
  cache:
    image: redis
    container_name: cache
    ports:
      - 6379
    networks:
      default:
        aliases:
         - cache.hein.internal

  queue:
    image: redis
    container_name: queue
    ports:
      - 6379
    networks:
      default:
        aliases:
         - queue.hein.internal